rango/urls.py
from django.conf.urls import url
from . import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.abount, name='about'),
    url(r'^category/(?P<slug>[\w\-]+)/$', views.CategoryDetailView.as_view(), name='show_category'),
    url(r'^add_category/$', views.add_category, name='add_category',),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
    url(r'^edit_profile/(?P<username>[\w\-]+)/$', views.update_profile, name='edit_profile'),
    url(r'^profiles/$', views.ListProfiles.as_view(), name='profiles'),
    url(r'^like/$', views.like_category, name='likes'),
    url(r'^suggest/$', views.suggest_category, name='suggestion'),
]

tango/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


from rango import views
from tango import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', views.MyRegistrationVIew.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


    class Meta:
        verbose_name = "目录"
        verbose_name_plural = "目录"

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    first_visit = models.DateTimeField(null=True)
    last_visit = models.DateTimeField(null=True)

    class Meta:
        verbose_name = '页面'
        verbose_name_plural = '页面'

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = '用户信息'

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Please enter the title of page.')
    url = forms.URLField(max_length=200, help_text='Please enter the URL of page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category','last_visit', 'first_visit')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')


class UserProfileForm(forms.ModelForm):
    # website = forms.URLField(required=False)
    # picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')
        #exclude = ('user',)

rango/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.http import HttpResponse

from registration.backends.simple.views import RegistrationView
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView

from .models import Category, Page, UserProfile
from .forms import CategoryForm, PageForm, UserProfileForm
from datetime import datetime


# Create your views here.
def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context = {'categories':category_list, 'page_list': page_list}

    visitor_cookie_handler(request)
    context['visits'] = request.session['visits']
    return render(request, 'rango/index.html', context=context)


def abount(request):
    return render(request, 'rango/abount.html')


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'rango/category.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pages = Page.objects.filter(category__slug=self.kwargs.get('slug')).order_by('-views') # = Page.objects.filter(category=category)
        context.update({
            'pages': pages,
        })
        return context


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
        return redirect('rango:index')
    return render(request, 'rango/add_category.html', context={'form': form})

@login_required
def like_category(request):
    category_id = None
    likes = 0
    if request.method == 'GET':
        category_id = request.GET['category_id']
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        category.likes += 1
        category.save()
        likes = category.likes
    return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)
    return render(request, 'rango/cats.html', {'cats': cat_list})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.save()
                return redirect(reverse('rango:show_category', kwargs={'slug': category_name_slug}))
        else:
            print(form.errors)
    context = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context)


class MyRegistrationVIew(RegistrationView):
    # 注册成功跳转
    def get_success_url(self, user=None):
        return reverse('rango:register_profile')

# 记录页面浏览数
def track_url(request):
    page_id = None
    if request.method == 'GET':
         page_id = request.GET.get('page_id')
    if page_id:
        try:
            page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))
        page.views += 1
        if page.first_visit == None:
            page.first_visit = page.last_visit = datetime.now()
        page.last_visit = datetime.now()
        page.save()
        return redirect(page.url)
    return redirect(reverse('rango:index'))

@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect(reverse("rango:index"))
        else:
            print(form.errors)
    context = {'form': form}
    return render(request, 'rango/profile_registration.html', context=context)


class ProfileDetailView(DetailView):
    model = UserProfile
    template_name = 'rango/profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        userprofile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
        context.update({
            'selecteduser': user,
            'userprofile': userprofile,
            'form': form
        })
        return context

@login_required
def update_profile(request, username):
    user = get_object_or_404(User, username=username)
    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    # 指定instance参数， 则使用已存在的对象来生成form对象，而不会生成新的对象
    form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
    if form.is_valid():
        form.save()
        return redirect('rango:profile', user.pk)


class ListProfiles(ListView):
    model = UserProfile
    template_name = 'rango/list_profiles.html'
    context_object_name = 'profiles'



def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

templates/rango/abount.html
{% extends 'rango/base.html' %}

{% block title %} About {% endblock %}

{% block body %}
    <button class="btn btn-primary" id="about-btn">Click me</button>
    <p id="msg">This is a example</p>
    <p>This is another example</p>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title %}Add a Category{% endblock %}

{% block body %}
    <form style="margin-top: 20px" role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br/>
            {{ field }}<br/>
            {% endfor %}<br/>
        <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
    </form>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body %}
    {% if category %}
        <form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
            <h2 class="form-signin-heading"> Add a Page to <a href="/rango/category/{{category.slug}}/">{{ category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
                {% endfor %}<br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page </button>
        </form>
    {% else %}
    <p>This is category does not exist.</p>
    {% endif %}
{% endblock %}

templates/rango/base.html
{% extends 'rango/base_bootstrap.html' %}

	<!-->


	<!DOCTYPE html>
	{% load staticfiles %}
	{% load rango_template_tags %}
	<html>
	<head>
		<title>
			Rango -
			{% block title %}
			How to Tango with Django!
			{% endblock %}
		</title>
	</head>
	<body>

		<div>
            <ul class="nav nav-list">
                <li class="nav-header">Type to find a category</li>
                <form>
                    <li>
                        <input class="search-query form-control" type="text" name="suggestion" value="" id="suggestion" /></li>
                </form>
            </ul>
            <hr>
            <div id="cats"></div>
		</div>

		<div>
			{% block body %}
			{% endblock %}
		</div>
		<hr />
{#		<div>#}
{#			<ul>#}
{#				<li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>#}
{#				<li><a href="{% url 'rango:about' %}">About</a></li>#}
{#				<li><a href="{% url 'rango:index' %}">Index</a></li>#}
{#                <li><a href="{% url 'rango:profiles' %}">List Profiles</a></li>#}
{#			</ul>#}
{#		</div>#}
	</body>
	</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load rango_template_tags %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

      <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
      <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>
    <script src="{% static "js/rango-ajax.js" %}"></script>

  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:profile' user.pk %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:profiles' %}">List Profiles</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">

            <ul class="nav nav-pills flex-column" style="padding: 5px">
		        <li class="nav-item">Type to find a category</li>
	            <form>
			        <li class="nav-item"><input class="search-query form-control" type="text"
				        name="suggestion" value="" id="suggestion" />
			        </li>
		        </form>
	        </ul>
            <hr />
	<div id="cats">
	</div>


        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
         {% block body %}{% endblock %}


        </div>
      </div>
    </div>

     <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
 <!--
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
 -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <!--
    <script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="{% static "js/rango-ajax.js" %}"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ category.name }}
{% endblock %}

{% block body %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{category.id}}" class="btn btn-primary btn-sm" type="button">Like</button>
            {% endif %}
        </div>

        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                        {% if page.views > 1 %}
                            {{ page.views }} viwes
                        {% else %}
                            {{ page.views }} view
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if request.user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% endif %}

    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
	{% load staticfiles %}
	{% block title %}
		Index
	{% endblock %}

	{% block body %}

	<div class="jumbotron" style="margin-top: 20px">
		<h1 class="display-3">Rango says...</h1>
		{% if user.is_authenticated %}
			<p class="lead">hey there {{ user.username }}</p>
		{% else %}
			<p class="lead">hey there partner! </p>
		{% endif %}

 	</div>

		<div class="row marketing">
			<div class="col-lg-6">
				<h4>Most Liked Categories</h4>
				<p>
		         	{% if categories %}
		             <ul class="list-group">
		                 {% for category in categories %}
		                 	<li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a> <span class="badge badge-pill badge-primary">{{category.likes}}</span></li>
		                 {% endfor %}
		             </ul>
		        {% else %}
		             <strong>There are no categories present.</strong>
		        {% endif %}

				</p>

			</div>
			<div class="col-lg-6">
				<h4>Most Viewed Pages</h4>
				<p>
				{% if page_list %}
				<ul class="list-group">
				{% for page in page_list %}
{#				 <li class="list-group-item"><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a> <span class="badge badge-pill badge-primary">{{page.views}}</span></li>#}
                {% endfor %}
                </ul>
				{% else %}
				<strong>There are no categories present.</strong>
			 {% endif %}
				</p>
			</div>
		</div>

		<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
        <img src="{{ MEDIA_URL }}/profile_images/man-888591__340.jpg" />
	{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}
{% block title %}User Profiles{% endblock %}
{% block body %}
<h1>User Profiles</h1>
<div class="panel">
    {% if profiles %}
        <div class="panel-heading">
        <!-- Display search results in an ordered list -->
            <div class="panel-body">
                <div class="list-group">
                    {% for listuser in profiles %}
                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <img width="32" height="32" src={% if listuser.picture %}{{ listuser.picture }}{% else %}"http://lorempixel.com/64/64/people/"{% endif %} />
                            <a href="{% url 'rango:profile' listuser.user.pk %}">{{ listuser.user.username }}</a>
                        </h4>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
         <p>There are no users for the site.</p>
    {% endif %}
</div>
{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}{{ selecteduser.username }} Profile {% endblock %}
{% block body %}
    <h1 style="margin-top: 20px">{{selecteduser.username}} Profile</h1>
    <img style="margin-bottom: 10px" src="{{ MEDIA_URL }}{{userprofile.picture }}" width="300" height="300" alt="{{selecteduser.username}}" />
    <br/>
    <div>
        {% if selecteduser.username == request.user.username %}
        <form method="post" action="{% url 'rango:edit_profile' user.username %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
        </form>
        {% else %}
            <p><strong>Website:</strong> <a href="{{userprofile.website}}">
            {{userprofile.website}}</a></p>
        {% endif %}
    </div>
    <div id="edit_profile"></div>
{% endblock %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}

{% block title %}
Registration - Step 2
{% endblock %}

{% block body %}
    <h1>Registration - Step 2</h1>
    {% if request.user.is_authenticated %}
    <form style="margin-top: 20px" enctype="multipart/form-data" action="{% url 'rango:register_profile' user.username %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
    {% endif %}
{% endblock %}